### ISSUE TITLE
Prevent accidentally closing page with an "Are you sure?" alert

### ISSUE THREAD

**Issue by 2sh** [iccanobif/gikopoi2#114]

**Comment by iccanobif** [comment]
tried with this code, as suggested here: https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload

``
            window.addEventListener("beforeunload", ev => {
                ev.preventDefault(); // If you prevent default behavior in Mozilla Firefox prompt will always be shown
                // Chrome requires returnValue to be set
                e.returnValue = '';
            })
``

Seems to work on firefox but not on chrome, though...
