### ISSUE TITLE
Palemoon problems

### ISSUE THREAD

**Issue by 153** [iccanobif/gikopoi2#120]
As of the latest update, Pale Moon can't connect to a room.

Palemoon also cannot send/receive streams.

**Comment by 153** [comment]
It can now connect (just takes a while).
Still can't send/receive streams.

**Comment by 2sh** [comment]
Are there any errors in the console?

**Comment by iccanobif** [comment]
Pale Moon thinks that WebRTC is not "useful or desired".
https://www.palemoon.org/technical.shtml

Hence, gikopoipoi can't support Pale Moon (or at the very least, streams will never work there).
