### ISSUE TITLE
isRedrawRequired doesn't work on unfocused windows when other users change room

### ISSUE THREAD

**Issue by iccanobif** [iccanobif/gikopoi2#150]
- login in one window
- login in another window (make sure both windows are visible in your screen)
- move inside the dev lounge from the second window
- in the first window, the avatar from the second window's user looks like it's stuck on the dev lounge door
- as soon as you click on the first tab, a redraw is finally successfully done and the stuck avatar disappears

**Comment by 2sh** [comment]
The canvas objects list wasn't being updated when users joined or left. Fixed now.
