### ISSUE TITLE
timestamps in log?

### ISSUE THREAD

**Issue by iccanobif** [iccanobif/gikopoi2#158]
Thoughts?

> ko: thoughts on chat timestamp option? @iccanobif@work
> iccanobif@work: i have mixed feelings on timestamps, tbh
> dinghy: they seem like bloat
> iccanobif@work: i like to keep the log clean and uncluttered, but i agree that they can be useful
> iccanobif@work: could be an opt-in setting
> iccanobif@work: on the other hand, gikopoi being a bit less convenient to use than a regular chat is also a feature
> dinghy: well
> dinghy: what would a time stamp really tell you
> dinghy: either people are currently talking, or they're ghosts
> iccanobif@work: true

**Comment by 2sh** [comment]
Mouseover tooltip with the timestamp in it maybe

**Comment by Shaddox** [comment]
I'd say  it's a pretty good idea. You can better evaluate who's been afk for how long.
