### ISSUE TITLE
Unable to stream out audio with Basilisk XP browser

### ISSUE THREAD

**Issue by pachuco** [iccanobif/gikopoi2#178]
https://o.rthost.win/basilisk/ using latest Basilisk52.

Checked if webrtc enabled and functioning. Seems ok.
Receiving video and audio stream is ok.
Attempted to stream out audio, got greeted by "Warning: Unable to obtain media.".
In devconsole, got following message:
- Date 2021-03-07T18:25:07.412Z TypeError: Promise.allSettled is not a function
- Stack trace:
- wantToStartStreaming@https://gikopoi2.herokuapp.com/scripts/main.js:1505:46
- invokeWithErrorHandling@https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js:1863:20
- invoker@https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js:2188:16
- add$1/original._wrapper@https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js:7547:18

**Comment by 2sh** [comment]
We only really support Firefox, Chrome and Edge. Workarounds for other browser are more effort than we can provide. allSettled is quite important and we don't want to make the code less clear with workarounds.

**Comment by iccanobif** [comment]
Mmm, found a polyfill for allSettled: https://github.com/amrayn/allsettled-polyfill/blob/master/index.js

It's true that we make no effort to support "alt" browsers, but for this particular case the workaround is simple enough so I don't mind adding it.

But yeah, no promises about poipoi working great on browsers other than firefox and chrome
