### ISSUE TITLE
speech synthesis

### ISSUE THREAD

**Issue by iccanobif** [iccanobif/gikopoi2#179]
https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis

**Comment by 2sh** [comment]
and maybe bouyomi chan

**Comment by 2sh** [comment]
wonder if bouyomi chan gets added as a voice

**Comment by iccanobif** [comment]
done! (not sure about bouyomi-chan, but gen people seem to be happy with what we have now)
