### ISSUE TITLE
Text to speech issues

### ISSUE THREAD

**Issue by 153** [iccanobif/gikopoi2#186]
If a user is posting obnoxiously long messages in an attempt to sabotage TTS, there is no fix. 

* Leaving the room and re-entering does not seem to interrupt the playlist 
* Disabling TTS does not interrupt the current playlist 

One or both of these should immediately halt TTS. 
Then, re-enabling TTS should play nothing until a new line of text is received.

**Comment by iccanobif** [comment]
right, should be easily fixed by calling this when leaving a room or disabling TTS: https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis/cancel
