### ISSUE TITLE
Minor improvements

### ISSUE THREAD

**Issue by 153** [iccanobif/gikopoi2#19]
tripcode: 
    name#test -> crypt(key="test", salt="es") -> last 10 chars 
    (bonus points: Replace any of the characters in :;<=>?@[\]^_` with the corresponding character from ABCDEFGabcdef. )

/me : 
    When a line of text is entered such as /me does a thing,
    show * Name does a thing

**Comment by iccanobif** [comment]
will do tripcodes with this https://www.npmjs.com/package/tripcode

**Comment by 2sh** [comment]
Why replace those characters for the bonus points?

**Comment by iccanobif** [comment]
Dunno, I think that it's more than enough to have 4chan compatible tripcodes, and now we have them.
Closing this issue for now (I think the /me stuff is kinda gay, gikopoi is not IRC).
