### ISSUE TITLE
if the socket from the listener's side drops, taken streams don't automatically reconnect

### ISSUE THREAD

**Issue by iccanobif** [iccanobif/gikopoi2#216]

**Comment by 2sh** [comment]
How long was the listener's side dropped for? It does turn of the taking stream after a while

**Comment by iccanobif** [comment]
it was very quick (less than a couple of seconds).
suddenly the stream had stopped, the "take stream" button was instantly visible and when i looked at the javascript console log there was the usual error message i get when the socket dies and needs to reconnect.

**Comment by 2sh** [comment]
Oh right. I think that causes it to remove and add all the stream slots again

**Comment by 2sh** [comment]
Is this still a thing?

**Comment by iccanobif** [comment]
haven't experienced this problem anymore... i guess we can close this issue and only investigate if it happens again

**Comment by 2sh** [comment]
Sounds good
