### ISSUE TITLE
mention noise

### ISSUE THREAD

**Issue by 2sh** [iccanobif/gikopoi2#240]
a different noise for when your name gets mentioned. just a different pitch maybe so it's not more annoying.
when I have the ping on I find myself ignoring it sometimes

also optionally only have the mention noise maybe

**Comment by iccanobif** [comment]
good idea, i can make a different sound for messages that have a mention.
how do we decide whether a message has a mention or not? just if it containes the user's name (might be annoying if your name is a single letter or a very common word) or should it be something like @username?

| also optionally only have the mention noise maybe

that would also be nice, maybe with a separate volume slide, but visible only in the settings popup, so we don't clutter the main page?

**Comment by 2sh** [comment]
Just when mentioned I think, `/\bUSER\b/i` maybe. @username feels a bit too social media-ish. would be kinda awkward seeing it in gikopoi I think

**Comment by 2sh** [comment]
a separate volume slide to make it louder or quieter than the normal sound?

**Comment by iccanobif** [comment]
we keep the single volume slider we already have in the main page, and add the following options in the settings popup (with these defaults):

Message sound: ☒
Name mention sound: ☐
Custom mention sound words (Comma separated or regex): [  ]
