### ISSUE TITLE
Keep showing people in #list who have already left the room for a while

### ISSUE THREAD

**Issue by 2sh** [iccanobif/gikopoi2#250]
So that you can ban the sneaky spammers who come in, send a message and immediately leave again. They could be greyed out in the list maybe

**Comment by iccanobif** [comment]
in alternative, we could display one extra line only for the disconnected user whose message has been highlighted in the log. that way we don't need to keep a list in memory with "recently disconnected users", we can just use the id and username from the log and display it at the top of the #list screen

**Comment by 2sh** [comment]
That's a better idea

**Comment by iccanobif** [comment]
done and merged
