### ISSUE TITLE
Stream viewer/listener count?

### ISSUE THREAD

**Issue by 2sh** [iccanobif/gikopoi2#253]

**Comment by iccanobif** [comment]
not sure about this... it'd be very sad for a streamer in a room with 15 users to see that only one or two are watching, and it might make people stream less

**Comment by 2sh** [comment]
yeah... kot asked about it but unsure about it too for the same reason

**Comment by iccanobif** [comment]
closing this issue for now, i guess we can talk about this again if there's really a demand for it (which i doubt)
