### ISSUE TITLE
ban the weird unicode characters used by 8ba3fc39-698a-4ebf-b501-7ca91fffc8f1

### ISSUE THREAD

**Issue by iccanobif** [iccanobif/gikopoi2#255]

**Comment by iccanobif** [comment]
better idea: display username and tripcode in two different lines in the canvas

**Comment by roris** [comment]
You could also display the username part and tripcode part in different colors, while keeping them on the same line

**Comment by iwamizawa-software** [comment]
tripcode('') return ''
convert XXXXXXXXXX# to XXXXXXXXXX◆
RLO insert to first charactor
display ◆XXXXXXXXXX(RLO)
no need ◆ when zero length password
https://en.wikipedia.org/wiki/Bidirectional_text#Table_of_possible_BiDi_character_types

**Comment by iccanobif** [comment]
The old gikopoi returns "◆fnkquv7jY2" for empty tripcode keys, so i could do that too.

**Comment by iccanobif** [comment]
I'll keep BiDi characters available, I like to see what tricks people can come up with them
