### ISSUE TITLE
When copying from the log, the seconds part of the timestamp should be zero padded

### ISSUE THREAD

**Issue by roris** [iccanobif/gikopoi2#284]
Currently the copied text is like this, if the seconds is less than 10:

```
[2021.05.24 1:45:2] Anonymous: ;~(
[2021.05.24 1:46:6] roris: i have reached my quota for today
```

**Comment by roris** [comment]
Just noticed that the hours part is not zero padded either. Now I'm guessing this is intentional.

**Comment by iccanobif** [comment]
ah no it wasn't intentional, i just noticed the problem after installing in production and eventually forgot to fix it
