### ISSUE TITLE
use real stage names

### ISSUE THREAD

**Issue by iccanobif** [iccanobif/gikopoi2#29]
![image](https://user-images.githubusercontent.com/414953/103436344-b71e2980-4c1a-11eb-976a-365e643eace9.png)

**Comment by 153** [comment]
In English: 

```
sid="long_st" name="Eel Track"
sid="jinja" name="Shrine"
sid="jinja_st" name="Shrine Entrance"
sid="school_ground" name="School: Schoolyard"
sid="bar774" name="Underground Town: Bar 774"
sid="izakaya774" name="Underground Town: Drunker's Bar"
sid="basement" name="Underground Town"
sid="bar" name="Bar"
sid="school_st" name="School Crossing"
sid="bar_st" name="Bar Street"
sid="admin_st" name="Kanrinin Street"
sid="admin" name="Developer's Lounge"
sid="admin_bar" name="Admin's Bar"
sid="cafe_st" name="Cafe Vista"
sid="enkai" name="Banqueting Hall"
sid="idoA" name="Well A"
sid="idoB" name="Well B"
sid="busstop" name="Bus Stop"
sid="school" name="School: Classroom"
sid="school_rouka" name="School: Hallway"
sid="school_international" name="School: Cultural Room"
sid="school_pc" name="School Computer Lab"
sid="seashore" name="Seashore"
sid="radio" name="Radio Studio"
sid="radio_room1" name="Radio Studio 1"
sid="radio_room2" name="Radio Studio 2: BEAT GIKO"
sid="radio_room3" name="Radio Studio 3: G-SQUID"
sid="radio_gakuya" name="Radio Studio: Dressing Room"
sid="radio_backstage" name="Radio Studio: Greenroom"
sid="yatai" name="Sushi Vendor"
sid="kaidan" name="Hilltop Stairway"
sid="takadai" name="Hilltop"
```

**Comment by iccanobif** [comment]
In japanese:

sid="jinja" name="神社" 
sid="jinja_st" name="神社入り口" 
sid="long_st" name="鰻道" 
sid="school_ground" name="学校 校庭" 
sid="bar774" name="地下街 バー774" 
sid="izakaya774" name="地下街 居酒屋 名無し" 
sid="basement" name="地下街" 
sid="bar" name="バー" 
sid="school_st" name="学校通り" 
sid="bar_st" name="バー通り" 
sid="admin_st" name="開発局通り" 
sid="cafe_st" name="カフェ通り" 
sid="busstop" name="バス停" 
sid="idoA" name="井戸Ａ" 
sid="idoB" name="井戸Ｂ" 
sid="school" name="学校 教室" 
sid="admin" name="開発局" 
sid="seashore" name="海岸" 
sid="admin_bar" name="秘密のバー" 
sid="radio" name="ラヂヲ局" 
sid="radio_room1" name="ラヂヲ局 第1スタジオ" 
sid="yatai" name="屋台" 
sid="kaidan" name="高台の階段" 
sid="takadai" name="高台" 
sid="radio_gakuya" name="ラヂヲ局 楽屋" 
sid="radio_backstage" name="ラヂヲ局 舞台裏" 
sid="radio_room2" name="ラヂヲ局 第2スタジオ BEAT GIKO" 
sid="radio_room3" name="ラヂヲ局 第3スタジオ G-SQUID" 
sid="school_rouka" name="学校 廊下" 
sid="school_international" name="学校 国際科教室" 
sid="school_pc" name="学校 パソコンルーム" 
sid="enkai" name="宴会場"
