### ISSUE TITLE
Add touch-action: manipulation;

### ISSUE THREAD

**Issue by iwasa-kosui** [iccanobif/gikopoi2#301]
In iOS Safari, if the user touches twice buttons rapidly, Safari zooms into around the button.
It is inconvenient when the user just want to move with the button.

However, probably some users want to zoom them.
So that, we cannot make the browser deny zoom.

When you set `touch-action: manipulation` to the button, it can avoid zooming when the user touches twice buttons rapidly, and the user can zoom with double finger.

**Comment by iccanobif** [comment]
Thank you.
So adding ``button { touch-action: manipulation: }`` to the CSS should be enough?

**Comment by iwasa-kosui** [comment]
I think it works!

**Comment by iccanobif** [comment]
Perfect, I'll close this issue then. The fix will be available in the next release later tonight.
