### ISSUE TITLE
light background image

### ISSUE THREAD

**Issue by iccanobif** [iccanobif/gikopoi2#305]
kot's proposals (the ones i like the best are the first two , the third one is very good but it kinda feels too blatantly stolen from the old giko, to me):

![image](https://user-images.githubusercontent.com/414953/122132232-c0065e80-ce3a-11eb-9add-280f76a03a6c.png)

![image](https://user-images.githubusercontent.com/414953/122132280-d6acb580-ce3a-11eb-9759-191448147aa2.png)

![image](https://user-images.githubusercontent.com/414953/122132213-b41a9c80-ce3a-11eb-869f-2a15ad3b3498.png)

![image](https://user-images.githubusercontent.com/414953/122132265-cf85a780-ce3a-11eb-84a1-78ef591cb857.png)

**Comment by feored** [comment]
how about using the ika image and recoloring it to fit the position & color of the fishes?
