### ISSUE TITLE
bug with streamers + other people blocked is still there, apparently

### ISSUE THREAD

**Issue by iccanobif** [iccanobif/gikopoi2#326]
超シーシャ人◆Shisha.3is：俺が配信してるとして
超シーシャ人◆Shisha.3is：俺があぼってるやつが配信にあがったら
超シーシャ人◆Shisha.3is：俺が落ちるバグ

**Comment by iwamizawa-software** [comment]
Maybe cause is this
```
userRoomEmit(user, user.areaId, user.roomId, "server-update-current-room-streams", toStreamSlotDtoArray(user, roomState.streams))
```
https://github.com/iccanobif/gikopoi2/blob/1f4f01f2d5b6c37c91be704e081c23dc98c72730/index.ts#L593
https://github.com/iccanobif/gikopoi2/blob/1f4f01f2d5b6c37c91be704e081c23dc98c72730/index.ts#L1537

If user is blocked, shisha is null by toStreamSlotDtoArray
userRoomEmit cannot use on server-update-current-room-streams

https://github.com/iccanobif/gikopoi2/blob/1f4f01f2d5b6c37c91be704e081c23dc98c72730/index.ts#L468
please try
