### ISSUE TITLE
video getting stuck sometimes

### ISSUE THREAD

**Issue by iccanobif** [iccanobif/gikopoi2#327]
- it happened often during piano otoko's stream
- probably not a load problem, since there was only one other stream active at the moment
- only his stream got stuck, while the other kept playing like normal
- dropping and re-getting the stream works

Possible workaround: check document.getElementById("received-video-0").currentTime every few seconds and if the value hasn't increased, automatically drop and get again (i couldn't check if currentTime actually stops increasing during these freezes)

**Comment by 2sh** [comment]
I think this is fixed now
