### ISSUE TITLE
yatai room is broken

### ISSUE THREAD

**Issue by iccanobif** [iccanobif/gikopoi2#328]
![image](https://user-images.githubusercontent.com/414953/133310438-ac95344a-0042-4609-b105-499cd32d0bb6.png)

should be:

![image](https://user-images.githubusercontent.com/414953/133310466-1db95e28-9a17-4574-b7b2-604868bd9f4f.png)

**Comment by 2sh** [comment]
Looks ok to me... Did it just not load right maybe?

**Comment by 2sh** [comment]
Weird. Just tried it on Firefox on Windows too and it's fine for me. Maybe that part got corrupted somehow and it's cached it.

Like with the characters, maybe putting all the room's images into a json would make it more consistent.

**Comment by iwamizawa-software** [comment]
Is file name "counter.***" blocked?
Can you rename counter.svg to table.svg?
