### ISSUE TITLE
[FEATURE REQ] spoopy gost

### ISSUE THREAD

**Issue by 153** [iccanobif/gikopoi2#335]
Similar to `#henshin`, a fun "Halloween" function that would be fairly simple to code would be `#yurei` command, that makes you appear as an AFK user, even when you move or talk. A second `#yurei` would reverse the toggle, similar to how `#henshin` operates. 

TL note: henshin = transform, yurei = ghost. 
`#shine` (imperative "die" i.e. "go die") also works.

**Comment by 2sh** [comment]
Maybe next Halloween
