### ISSUE TITLE
[ART BUG] Feet stick out from under trash can

### ISSUE THREAD

**Issue by 153** [iccanobif/gikopoi2#337]
![](https://i.imgur.com/hSmDrJJ.png)

**ISSUE:**
Some foreground sprites do not "block" the full tile around them, resulting in a bug like these where feet stick out from under the garbage can. This may be an intentional "feature" but it's something I noticed. 

**SOLUTION:** 
Modify `static/rooms/admin_st/trash-bin2.svg` to include the sidewalk tile from `static/rooms/admin_st/background.svg` so that feet are properly concealed.

**Comment by iccanobif** [comment]
would look weird when the avatar moves towards the go table to get out of the trash bin. this sprite is broken for aramaki too, anyway.
