### ISSUE TITLE
[FEATURE REQ] "auto clear bubble"

### ISSUE THREAD

**Issue by 153** [iccanobif/gikopoi2#347]
A user today suggested a toggle-able settings option to automatically clear the text bubble after a short timer (say, 30 seconds) -- this could be selected by default, and can be deselected by more skilled users based on need (e.g. for sharing AA art, saying "afk", returning to tradition, etc)

**Comment by 153** [comment]
Another fix to the general problem (people "abusing" bubbles) is "hide bubbles" in menu.

**Comment by iccanobif** [comment]
i don't like the idea of adding more complexity just because some people didn't like gyahaha's bubbles
