### ISSUE TITLE
Streams randomly dropping

### ISSUE THREAD

**Issue by 153** [iccanobif/gikopoi2#357]
A Japanese user requested the developers be informed that streams randomly drop; I don't currently see an issue for this. I've also noticed this issue in my streams: a stream may drop after 5 minutes and then run fine for over an hour; a stream may drop twice in 10 minutes, then work again for 20 or 30 minutes, then drop again. 

Could this be a result of too many people streaming at one time?

**Comment by 2sh** [comment]
A time for when these drops occur would be appreciated so we know what to look for in the logs.
Recently there have been code changes around streaming and the streaming server has been switched, so it could either be a new bug or the new server can't handle the load.

**Comment by 153** [comment]
I'll try to make notes of when it happens [here](https://tanasinn.vip/games/gikopoi/drops); it may be my connection, but I've been noticing it happening with other users. I do not know enough to determine whether it's the server or users' internet   -- their stream will still be open and they'll be chatting; other people have to alert them to the problem.

**Comment by iccanobif** [comment]
just looked in the logs and found some automatic restarts initiated by the cloud platform. it's something that normally happens every 24 hours but sometimes they do it more times when they're doing maintenance on their infrastructure. not much we can do about this other than making streams persistent across node.js restarts (something that's already being worked on)
