### ISSUE TITLE
Bizarre warp

### ISSUE THREAD

**Issue by 153** [iccanobif/gikopoi2#36]
Just logging this here for historical purposes; 

A bizarre warp will bring players to the street in front of the school, without a way to exit the zone. I have numbered the arrows 1, 2, and 3 in Roman numerals because Gikopoi2 is an Italian software. 

![](https://i.imgur.com/95c3Gpa.png)  
<img src="https://i.imgur.com/95c3Gpa.png" />   
https://i.imgur.com/95c3Gpa.png

**Comment by iccanobif** [comment]
oh noes Giko hell! :O!
