### ISSUE TITLE
[NETWORK BUG] Stream users timeout during stream

### ISSUE THREAD

**Issue by 153** [iccanobif/gikopoi2#361]
A user has reported that his chat and the stream he was watching both stopped for him. He could still walk around, but when he tried to send a message, it did not appear in the log. A refresh fixes this issue. 

Username: killsushi

**Comment by 153** [comment]
All day today, multiple users have been experiencing heavy slowdown / lag / freezes. This is strange because INT has had <10 active users for most of the day, and GEN currently has <60 users (likely fewer during UTC-09's late late hours). This may be related.

**Comment by 2sh** [comment]
Hopefully fixed now
