### ISSUE TITLE
[REQUEST] Starting a stream server not clear

### ISSUE THREAD

**Issue by 153** [iccanobif/gikopoi2#373]
I tried running a server, but my game crashes when I try to start a stream. It appears I need to start a stream server somehow, but I'm in the dark as to how that is done. My temporary workaround is to simply disable streams in all rooms. Some more details on how to accomplish streams could be useful. I can write documentation if it helps. 

Side note, `yarn --ignore-engines` allowed me to make the game work.

**Comment by iccanobif** [comment]
you need a janus server. no support or documentation on how to set it up will be provided.
