### ISSUE TITLE
make mechanism for positioning characters correctly against large objects

### ISSUE THREAD

**Issue by iccanobif** [iccanobif/gikopoi2#374]
using lambdas instead of merely a focal point for the object? something else?

**Comment by iccanobif** [comment]
the lambda could be a "comparer", a function with obj1x, obj1y, obj2x and obj2y as parameters. the default comparer will implement the same formula as we do now to calculate the "priority" of both objects and just return priority1 - priority2. For complex objects, on the other hand, the custom comparer can do whatever strange hardcoded stuff we want.

**Comment by iccanobif** [comment]
It's probably better to give up on using comparers: a pair of objects might not have a particular ordering between each other but might depend on a _third_ object. For example, here we can't tell which of the two gikos should stay on top by just comparing them, we need to know the exact shape of another object.
![image](https://user-images.githubusercontent.com/414953/146671860-922b2f0c-7502-40a8-a858-b2781d0710dc.png)

According to this video (https://www.youtube.com/watch?v=yRZlVrinw9I) the solution is https://en.wikipedia.org/wiki/Topological_sorting (will have to study this stuff a bit more in detail though)). https://github.com/markv12/IsoSpriteSortingDemo

Another idea could be to automatically split objects in separate sprites (one for each tile in the map) and calculate the ordering for each of them from their specific position. Sounds complicated to implement and might affect performance, though.

**Comment by 2sh** [comment]
Tho I made it position the Konbini counter correctly now on my branch, there's probably still a much better way out there.
