### ISSUE TITLE
Many users + many messages, click name? crash

### ISSUE THREAD

**Issue by 153** [iccanobif/gikopoi2#384]
when there is a lot of activity, clicking on a chatter's name / streamer's name (to make the name in the message log red) makes some browsers crash. Sorry, I realize this is pretty subjective, but it's worth noting anyway.

**Comment by iccanobif** [comment]
it's not about being subjective, it's about giving at least the username of a user who experienced the issue so i can take a look at the logs. how am i supposed to troubleshoot this?

**Comment by 153** [comment]
iccanobif, just clicking bon's tripcode on my game after ~7 hours (rough guess) of connection in the bar and then shrine and then silo was enough to trigger this.

**Comment by vacaran2017** [comment]
https://github.com/iccanobif/gikopoi2/blob/bef82bd392480989075bb33c9e4ff4036ee5d8c6/static/scripts/main.js#L3045-L3051

I wonder if updating a `<style>` tag containing ```[data-user-id="<UUID>"] { color: red; }``` would be any better.
