### ISSUE TITLE
[FEATURE] modify message prefix

### ISSUE THREAD

**Issue by 153** [iccanobif/gikopoi2#385]
Timestamps could be available with checkbox, with a textbox with C-style strftime for input such as `%H:%M` or `%I:%M %p` or perhaps checkboxes for just the minute, eg. 

- anon `: message`
- sageru `Name: message`
- minute `:%M: Name: message` 
- standard `%H:%M: Name: message`

**Comment by iccanobif** [comment]
no, just use an awk script or something to edit the dates

**Comment by 153** [comment]
I don't know how to access "awk" feature of my Firefox or my Android's Google Chrome. This was meant to refer to clients, not server.
