### ISSUE TITLE
the \ character is handled strangely in usernames

### ISSUE THREAD

**Issue by 153** [iccanobif/gikopoi2#396]
When a user has \ in the name, it's printed normally in the overworld, but treated like a yen character in the chatlog. This seems unintentional; at the least, it's inconsistent.

**Comment by vacaran2017** [comment]
The backslash is a yen sign in standard Japanese fonts because the ASCII location backslash was used for the yen sign in JIS: https://en.wikipedia.org/wiki/\#Confusion_with_¥_and_other_characters. This is probably not a problem in poipoi.

**Comment by 153** [comment]
@vacaran2017 it's still represented differently in the overworld vs speech bubbles / chatlog -- it's inconsistent even if it's not a "problem"

**Comment by iccanobif** [comment]
fixed some time ago when i changed the textbox's font to the same one used in the canvas
