### ISSUE TITLE
when copying from the log, messages from ignored users are also copied

### ISSUE THREAD

**Issue by iccanobif** [iccanobif/gikopoi2#403]
it's because those messages are still in the DOM even if they're not visible... not sure how to prevent this (probably not a big deal anyway)

**Comment by iccanobif** [comment]
Happens only when "Show in the log an indicator in place of the messages by ignored users" is on

**Comment by iwamizawa-software** [comment]
.ignored-message
{
    display: none;
    user-select: none;
}
