### ISSUE TITLE
Autoresume seems to be broken

### ISSUE THREAD

**Issue by iccanobif** [iccanobif/gikopoi2#407]

**Comment by iccanobif** [comment]
taking a stream right after it was started yelds a "No such feed" error... not sure when it's safe to take a stream, isReady being true doesn't seem to be enough...

**Comment by 2sh** [comment]
May have to look at the Janus responses and faff with the Janus library again....

**Comment by iccanobif** [comment]
in the meanwhile i committed here my attempt at setting isReady to true at the right moment when the stream _really_ is safe to take. I tried to do that when the rtc peer is in state "connected" for the streamer, but it still doesn't seem to work... No idea of which other event we can use to send this `user-stream-is-ready` message (if such an event can be captured on node.js's side, we can of course remove the `user-stream-is-ready` message completely). 
https://github.com/iccanobif/gikopoi2/tree/fix-autoresume

**Comment by iwamizawa-software** [comment]
https://github.com/iccanobif/gikopoi2/blob/edece27736c7e771fd6acc0ff698e0c57cb588b3/index.ts#L773-L775
replace into
```
janusHandle.onWebrtcUp(() =>
{
  stream.isReady = true
  sendUpdatedStreamSlotState(user)
})
```
