### ISSUE TITLE
Regex of Custom Mention Sound Pattern

### ISSUE THREAD

**Issue by linfloor** [iccanobif/gikopoi2#421]
I try setting notification to appear when triggered by words like "lin" instead of "telling", "killing", etc.

So I input 「\blin\b」 to Custom Mention Sound Pattern.
But when I output 「telling」, the notification still be trigger.

Is my syntax wrong so regex doesn't works?

**Comment by linfloor** [comment]
I have tried 「/\blin\b/」 but the notification still be trigger by 「telling」 or 「killing」.

**Comment by 2sh** [comment]
Like this?
![image](https://user-images.githubusercontent.com/6656120/169295429-15cf0399-7c6c-45e6-ba1a-05727b6b1a5e.png)
Both telling and killing don't trigger the sound for me when I do this.

**Comment by 2sh** [comment]
Oh do you log in with the name 「lin」? You need to untick the "Username Mention Sound" option then.

**Comment by linfloor** [comment]
Thank you ❤ it works!
I thought 「Username Mention Sound」 and 「Custum Mention Sound Pattern」are together.

My understanding is below:

「Username Mention Sound」
* The notification sound appear when someone's  conversation includes your username.
* But it is simple function, if your username often appear in some words, you should not tick on this function.
* For example, if your username is 「lin」, then words like 「link」,「killing」,「falling」 will trigger the notification sound.

「Custum Mention Sound Pattern」
* The notification sound appear when someone's  conversation includes the words that you set.
* If you don't use regex, the function is same as 「Username Mention Sound」, 
but you can edit what words can trigger by comma.
* If your username often appear in some words,, regex can help you solve.
* For example,  if your username is 「lin」, you can set 「/\blin\b/」to solve problem.
if you have two words AAA and BBB to set, you can set「/\bAAA\b|\bBBB\b/」

1. Surround regex by 「/」.
2. Surround any independ words by 「\b」.
3. For detect more words, connect words by 「|」.

**Comment by iccanobif** [comment]
looks like the problem is fixed so i'll close the ticket for now
