### ISSUE TITLE
stream in new tab bug

### ISSUE THREAD

**Issue by iccanobif** [iccanobif/gikopoi2#427]
1. open in new tab
2. drop stream without closing the new tab
3. get the stream again -> this step fails

should forcefully reattach the video element to the original page when dropping the stream, i guess

**Comment by iwamizawa-software** [comment]
https://github.com/iccanobif/gikopoi2/blob/c8fd4cd00a780ca0c7f9d4bdcb9d0075f8a50733/static/scripts/main.js#L2632

```
            if (this.detachedStreamTabs[streamSlotId])
            {
                this.detachedStreamTabs[streamSlotId].onbeforeunload();
                this.detachedStreamTabs[streamSlotId].close();
                this.detachedStreamTabs[streamSlotId] = null;
            }
```

**Comment by iwamizawa-software** [comment]
When streamer stop streaming without closing new tab, faild to getElementById
This code is not tested
