### ISSUE TITLE
kaminarisama - Hair transparency bug

### ISSUE THREAD

**Issue by 153** [iccanobif/gikopoi2#435]
![](https://i.imgur.com/wXJeUMa.png)

For unknown reasons, sometimes Kaminarisama's hair is much too translucent. 

I can make it look right again by disabling username background. Re-enabling username background does not make his hair become translucent again.

**Browser:** Google Chrome 103.0.5060.66
**OS:** Windows 11, build 22000

EDIT: when I alt-tabbed and returned, his hair became translucent again. Not sure what the exact trigger was.

**Comment by iccanobif** [comment]
not gonna touch that thing. looks "normal" without crisp mode
