### ISSUE TITLE
[suggestion] force default giko skin in drunker's bar/bar 774 to preserve actual anonymity

### ISSUE THREAD

**Issue by SeizonSenryaku** [iccanobif/gikopoi2#442]
To preserve actual anonymity, I think that forcing the default giko model/skin/whatever in these 2 rooms would make sense (and other forced-anon rooms that I may not be thinking of). I don't really see any reason not to do this, and if somebody wants to be anonymous this would help preserve it. Any user who's played gikopoi for more than a few weeks will pretty quickly recognize a player, especially on _for, using a model that few others use.
Case in point: A certain player was immediately recognized upon entering just now.

**Comment by iccanobif** [comment]
Dunno, here we are basically just keeping the same mechanism as the old gikopoi, and if someone really wants to be "anonymous" they can just log in with a different character than the one they usually use...
