### ISSUE TITLE
[FEATURE] tab complete user nicks

### ISSUE THREAD

**Issue by 153** [iccanobif/gikopoi2#449]
Tab completion of user nicks, as with IRC and other applications, would be a huge boon when replying to people in busy rooms. 

When several user nicks match the beginning of the space pre-fixed current text, cycle through a list of possible matches before returning to the original string. (eg: if Mario and maf are in a room, "hello ma[tab]" -> "hello Mario" -> "hello maf" -> "hello ma" ). 

Don't include tripcodes in tab complete, despite the possibility of multiple nicks having unique tripcodes.

**Comment by iccanobif** [comment]
no thanks
