### ISSUE TITLE
Scrollbar gets CSS from dark-mode even in normal theme

### ISSUE THREAD

**Issue by feored** [iccanobif/gikopoi2#458]
Kao mentioned this and I reproduced it without a problem.

The dark mode defines a background-color for the scrollbar, but since the light mode apparently doesn't and all stylesheets are linked in the page header, it seems that chrome (maybe other browsers as well) applies that background color even when dark-mode isn't selected.

Forcing every theme to have the same exact css selectors might work, but a way to swap stylesheets in and out on selection of a new theme so that only one stylesheet is active at a time is probably a better solution.

![image](https://user-images.githubusercontent.com/1587153/207636945-303249e3-9272-4e5f-a8a8-6ead08c7a14c.png)

**Comment by 2sh** [comment]
oh right. I added the css to the css file without adding any .theme-dark class woops
