### ISSUE TITLE
Login is too slow

### ISSUE THREAD

**Issue by iwamizawa-software** [iccanobif/gikopoi2#473]
https://github.com/iccanobif/gikopoi2/blob/51bcccf406d2b439756cc575ee5752ed3a2d1290/index.ts#L1485
/characters/regular download is 4sec

suggestion
```js
const regular = await getCharacterImages(false);
app.get("/characters/regular", async (req, res) =>
{
    try { res.json(regular) } catch (e) { res.end(stringifyException(e)) }
})
const crisp = await getCharacterImages(true);
app.get("/characters/crisp", async (req, res) =>
{
    try { res.json(crisp) } catch (e) { res.end(stringifyException(e)) }
})
```

<del>

And, 
https://github.com/iccanobif/gikopoi2/blob/7d9b22150d523d589b639fa6c001b9e751e99ca9/static/scripts/character.js#L142
each character waiting

suggestion
loadImages return promise array, and waiting all character promise at line 203

</del>

https://github.com/iccanobif/gikopoi2/blob/7d9b22150d523d589b639fa6c001b9e751e99ca9/static/scripts/character.js#L203
is 4sec

**Comment by 2sh** [comment]
Login time improved
