### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'document')

### ISSUE THREAD

**Issue by iwamizawa-software** [iccanobif/gikopoi2#484]
https://github.com/iccanobif/gikopoi2/blob/a7f13d825d896af4c724b70851d3c4093a578725/src/frontend/main.js#L1208

when this.detachedStreamTabs = [null], throw error.

Need if (this.detachedStreamTabs[i])

**Comment by iccanobif** [comment]
fixed with bc9f3af1fe6e0c7ee96d228be32775c80ee68094
