### ISSUE TITLE
Door only works when approached from side

### ISSUE THREAD

**Issue by 153** [iccanobif/gikopoi2#6]
Not sure if you knew this, but the door in the bar only works when approached from a side.
When approached from the "proper" direction, the user is briefly taken to the street before being warped back into the bar.

**Comment by iccanobif** [comment]
Yeah, warp still doesn't work in a number of situations, and it's still very much work in progress... Thanks for opening this issue anyway, I guess it'd be a good idea to start keeping track of what's missing to make this gikopoi usable.

**Comment by iccanobif** [comment]
more or less fixed, now
