### ISSUE TITLE
ability to ignore users

### ISSUE THREAD

**Issue by iccanobif** [iccanobif/gikopoi2#68]

**Comment by 2sh** [comment]
probably as part of the user list feature I'm thinking

**Comment by iccanobif** [comment]
a user list on the right side of the screen, right? so we can avoid having to properly handle clicks on the canvas, and it'd be different from the original giko, which we are NOT plagiarizing

**Comment by 2sh** [comment]
clicking people to block was a pain anyway if they went behind others. tho might get difficult if multiple people have the same name. could a number be temporarily added next the char's name in the canvas?
yeah originally thought on the right. tho maybe in a window as it's not something you'll need to see all the time and pressing the button to view the window could also show that number...?

**Comment by 153** [comment]
please don't add this feature, because then, i can't force people to chat with me.

**Comment by iccanobif** [comment]
one-way ignoring is live, closing this issue for now in case there's a demand for "real", two-way blocking
