### ISSUE TITLE
Feature request: dice rolling

### ISSUE THREAD

**Issue by 153** [iccanobif/gikopoi2#72]
eg `!roll 1d6`
=>
`You rolled 6`

`!roll 1d20+3`
=>
`You rolled 15 (12+3)`

`!roll 3d6`
=>
`You rolled 11 (2, 6, 3)`

**Comment by 2sh** [comment]
It could be a new room with clickable dice on the table, but a command doesn't feel very gikopoi-ish. Use discord or irc if you want that.
