### ISSUE TITLE
Feature request: "forced giko"

### ISSUE THREAD

**Issue by 153** [iccanobif/gikopoi2#74]
1. A checkbox is presented to players in the client. 
2. When checked, all players appear as "giko" and their name appears to be "giko"
3. This feature can be set as a cookie or via URL field

Along with https://github.com/iccanobif/gikopoi2/issues/71 this can make it easy for spontaneous anonymous group chats, similar to what the "underground" chatrooms offer, or what users of 4chan may prefer. 

The checkbox at login screen could appear next to the name field, and checking it disables the name field (grays it out).

In game, it could appear unlabelled by the arrow keys.

**Comment by iccanobif** [comment]
for anonymous chats i think that people can just go to the underground bar
